//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BlogDBModel", "FK__Post__BlogID__4CA06362", "Blog", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BlogTask.Blog), "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlogTask.Post), true)]

#endregion

namespace BlogTask
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BlogDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BlogDBEntities object using the connection string found in the 'BlogDBEntities' section of the application configuration file.
        /// </summary>
        public BlogDBEntities() : base("name=BlogDBEntities", "BlogDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogDBEntities object.
        /// </summary>
        public BlogDBEntities(string connectionString) : base(connectionString, "BlogDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogDBEntities object.
        /// </summary>
        public BlogDBEntities(EntityConnection connection) : base(connection, "BlogDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Blog> Blogs
        {
            get
            {
                if ((_Blogs == null))
                {
                    _Blogs = base.CreateObjectSet<Blog>("Blogs");
                }
                return _Blogs;
            }
        }
        private ObjectSet<Blog> _Blogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Post> Posts
        {
            get
            {
                if ((_Posts == null))
                {
                    _Posts = base.CreateObjectSet<Post>("Posts");
                }
                return _Posts;
            }
        }
        private ObjectSet<Post> _Posts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Blogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogs(Blog blog)
        {
            base.AddObject("Blogs", blog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Posts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosts(Post post)
        {
            base.AddObject("Posts", post);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogDBModel", Name="Blog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Blog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Blog object.
        /// </summary>
        /// <param name="blogId">Initial value of the BlogId property.</param>
        public static Blog CreateBlog(global::System.Int32 blogId)
        {
            Blog blog = new Blog();
            blog.BlogId = blogId;
            return blog;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                if (_BlogId != value)
                {
                    OnBlogIdChanging(value);
                    ReportPropertyChanging("BlogId");
                    _BlogId = StructuralObject.SetValidValue(value, "BlogId");
                    ReportPropertyChanged("BlogId");
                    OnBlogIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogId;
        partial void OnBlogIdChanging(global::System.Int32 value);
        partial void OnBlogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Blog_Name
        {
            get
            {
                return _Blog_Name;
            }
            set
            {
                OnBlog_NameChanging(value);
                ReportPropertyChanging("Blog_Name");
                _Blog_Name = StructuralObject.SetValidValue(value, true, "Blog_Name");
                ReportPropertyChanged("Blog_Name");
                OnBlog_NameChanged();
            }
        }
        private global::System.String _Blog_Name;
        partial void OnBlog_NameChanging(global::System.String value);
        partial void OnBlog_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Blog_Type
        {
            get
            {
                return _Blog_Type;
            }
            set
            {
                OnBlog_TypeChanging(value);
                ReportPropertyChanging("Blog_Type");
                _Blog_Type = StructuralObject.SetValidValue(value, true, "Blog_Type");
                ReportPropertyChanged("Blog_Type");
                OnBlog_TypeChanged();
            }
        }
        private global::System.String _Blog_Type;
        partial void OnBlog_TypeChanging(global::System.String value);
        partial void OnBlog_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Blog_Header
        {
            get
            {
                return _Blog_Header;
            }
            set
            {
                OnBlog_HeaderChanging(value);
                ReportPropertyChanging("Blog_Header");
                _Blog_Header = StructuralObject.SetValidValue(value, true, "Blog_Header");
                ReportPropertyChanged("Blog_Header");
                OnBlog_HeaderChanged();
            }
        }
        private global::System.String _Blog_Header;
        partial void OnBlog_HeaderChanging(global::System.String value);
        partial void OnBlog_HeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Blog_Description
        {
            get
            {
                return _Blog_Description;
            }
            set
            {
                OnBlog_DescriptionChanging(value);
                ReportPropertyChanging("Blog_Description");
                _Blog_Description = StructuralObject.SetValidValue(value, true, "Blog_Description");
                ReportPropertyChanged("Blog_Description");
                OnBlog_DescriptionChanged();
            }
        }
        private global::System.String _Blog_Description;
        partial void OnBlog_DescriptionChanging(global::System.String value);
        partial void OnBlog_DescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogDBModel", "FK__Post__BlogID__4CA06362", "Post")]
        public EntityCollection<Post> Posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Post>("BlogDBModel.FK__Post__BlogID__4CA06362", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Post>("BlogDBModel.FK__Post__BlogID__4CA06362", "Post", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogDBModel", Name="Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Post object.
        /// </summary>
        /// <param name="postId">Initial value of the PostId property.</param>
        public static Post CreatePost(global::System.Int32 postId)
        {
            Post post = new Post();
            post.PostId = postId;
            return post;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostId
        {
            get
            {
                return _PostId;
            }
            set
            {
                if (_PostId != value)
                {
                    OnPostIdChanging(value);
                    ReportPropertyChanging("PostId");
                    _PostId = StructuralObject.SetValidValue(value, "PostId");
                    ReportPropertyChanged("PostId");
                    OnPostIdChanged();
                }
            }
        }
        private global::System.Int32 _PostId;
        partial void OnPostIdChanging(global::System.Int32 value);
        partial void OnPostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Post_Description
        {
            get
            {
                return _Post_Description;
            }
            set
            {
                OnPost_DescriptionChanging(value);
                ReportPropertyChanging("Post_Description");
                _Post_Description = StructuralObject.SetValidValue(value, true, "Post_Description");
                ReportPropertyChanged("Post_Description");
                OnPost_DescriptionChanged();
            }
        }
        private global::System.String _Post_Description;
        partial void OnPost_DescriptionChanging(global::System.String value);
        partial void OnPost_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value, "CreationDate");
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BlogID
        {
            get
            {
                return _BlogID;
            }
            set
            {
                OnBlogIDChanging(value);
                ReportPropertyChanging("BlogID");
                _BlogID = StructuralObject.SetValidValue(value, "BlogID");
                ReportPropertyChanged("BlogID");
                OnBlogIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BlogID;
        partial void OnBlogIDChanging(Nullable<global::System.Int32> value);
        partial void OnBlogIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogDBModel", "FK__Post__BlogID__4CA06362", "Blog")]
        public Blog Blog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("BlogDBModel.FK__Post__BlogID__4CA06362", "Blog").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("BlogDBModel.FK__Post__BlogID__4CA06362", "Blog").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Blog> BlogReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("BlogDBModel.FK__Post__BlogID__4CA06362", "Blog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Blog>("BlogDBModel.FK__Post__BlogID__4CA06362", "Blog", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
